#
#      Swofty Parkour
#       Swofty#0001
#
#      Plugin Config
#

hologram-split-size: 0.3
# Must not be less than 1 and wouldn't recommend being over 10
leaderboard-display-size: 3
pressure-plate-types:
  # Valid types are 'IRON' and 'GOLD'
  start: "GOLD"
  checkpoint: "IRON"
  end: "GOLD"