name: SeniorTeamApplication
version: '${project.version}'
main: net.swofty.swoftyparkour.plugin.SwoftyParkour
api-version: 1.16
description: "A 1.19.2 configurable plugin intended for my application for Senior Team"
author: "Swofty"
