name: SwoftyParkour
version: '${project.version}'
main: net.swofty.parkour.plugin.SwoftyParkour
api-version: 1.16
description: "A 1.19.2 configurable plugin intended for making parkour courses"
author: "Swofty"
